# Import librairies

In [35]:
import pandas as pd
import numpy as np

In [36]:
# Load dataset
path="../../data/final_properties_dataset.csv"
properties=pd.read_csv(path,index_col=0)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',25)

# Get column names
properties.columns

properties

,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Terrace area,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building
0,https://immovlan.be/en/detail/apartment/for-sa...,1853.0,Strombeek-Bever,Apartment,apartment,235000.0,for sale,2.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,https://immovlan.be/en/detail/residence/for-sa...,2200.0,Herentals,House,residence,369000.0,for sale,3.0,378.0,NaN,0.0,NaN,1.0,NaN,1.0,NaN,300.0,2.0,NaN,0.0
2,https://immovlan.be/en/detail/apartment/for-sa...,1190.0,Vorst,Apartment,apartment,385000.0,for sale,2.0,100.0,NaN,0.0,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,https://immovlan.be/en/detail/residence/for-sa...,7100.0,La,House,residence,135000.0,for sale,3.0,125.0,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN
4,https://immovlan.be/en/detail/apartment/for-sa...,8301.0,Duinbergen,Apartment,apartment,595000.0,for sale,3.0,NaN,NaN,NaN,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13244,https://immovlan.be/en/detail/residence/for-sa...,9190.0,Stekene,House,residence,450000.0,for sale,3.0,170.0,NaN,0.0,NaN,0.0,NaN,1.0,NaN,300.0,3.0,NaN,4.0
13245,https://immovlan.be/en/detail/apartment/for-sa...,1030.0,Schaarbeek,Apartment,apartment,229000.0,for sale,1.0,72.0,1.0,0.0,NaN,0.0,NaN,0.0,NaN,NaN,3.0,0.0,1.0
13246,https://immovlan.be/en/detail/residence/for-sa...,6470.0,Sautin,House,residence,199000.0,for sale,3.0,134.0,NaN,0.0,1.0,1.0,NaN,1.0,NaN,1497.0,NaN,NaN,NaN
13247,https://immovlan.be/en/detail/residence/for-sa...,1200.0,Sint-Lambrechts-Woluwe,House,residence,1090000.0,for sale,5.0,243.0,2.0,0.0,NaN,1.0,NaN,1.0,NaN,237.0,2.0,0.0,1.0
13248,https://immovlan.be/en/detail/residence/for-sa...,2840.0,Rumst,House,residence,2300000.0,for sale,7.0,576.0,NaN,0.0,NaN,1.0,NaN,1.0,NaN,5778.0,4.0,NaN,2.0

# Step 1 : Data Cleaning
#### You have collected your data! So it's time to do a cleaning on it. A cleaned dataset is a dataset that doesn't contain any duplicates, is blank spaces or error-free. The rest of the analysis can be discarded if you neglect this step!

### No duplicates
### No blank spaces (ex: " I love python " => "I love python")
### No errors
### No empty values

In [37]:
# Get stats and infos about dataset
properties.describe()
properties.info()

# Check if duplicates by url --> bool
properties.URL.is_unique

#Check empty lines
empty_lines_price=properties[properties['Price'].isna() == True].index
empty_lines_area=properties[properties['Living Area'].isna()==True].index
empty_lines=empty_lines_price.append(empty_lines_area)

<class 'pandas.DataFrame'>
RangeIndex: 13249 entries, 0 to 13248
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   URL                     13249 non-null  str
 1   Zip code                13248 non-null  float64
 2   City                    13248 non-null  str
 3   Type of property        13249 non-null  str
 4   Subtype of property     13249 non-null  str
 5   Price                   13025 non-null  float64
 6   Type of sale            13249 non-null  str
 7   Number of rooms         12993 non-null  float64
 8   Living Area             12404 non-null  float64
 9   Fully equipped kitchen  4513 non-null   float64
 10  Furnished               8425 non-null   float64
 11  Open fire               1143 non-null   float64
 12  Terrace                 12666 non-null  float64
 13  Terrace area            0 non-null      float64
 14  Garden                  12300 non-null  float64
 15  Garden area             3020 non-null   float64
 16  Surface of the land     6195 non-null   float64
 17  Number of facades       10382 non-null  float64
 18  Swimming pool           4544 non-null   float64
 19  State of the building   10421 non-null  float64
dtypes: float64(15), str(5)
memory usage: 2.0 MB

Spaces in Name of City causes a problem (La Louvière > La)

We have floats instead of int

Zip is float instead of str

‘Terrace area’ → all NaN OK

Row 1179 no infos > drop: Ok

In [38]:
# Remove empty lines
properties=properties.drop(empty_lines,axis=0)

# Drop Terrace
properties.drop(['Terrace area'],axis=1,inplace=True)
properties[['Open fire','Furnished','Garden','Swimming pool','Terrace']]=properties[['Open fire','Furnished','Garden','Swimming pool','Terrace']].replace(np.nan,0)

# Remove spaces before and/or after if there are (>> strip)
properties=properties.apply(lambda x: x.str.strip() if x.dtype=="object" else x)

# Correct one specific value
properties.loc[properties.City=='La','City']="La Louvière"

# Garden area = 0 if Garden is False
properties.loc[properties.Garden == 0,'Garden area']=0

# Drop prop with price <10000
properties=properties[properties['Price']>=10000]

In [39]:
properties[properties['Price']>=10000]

,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building
1,https://immovlan.be/en/detail/residence/for-sa...,2200.0,Herentals,House,residence,369000.0,for sale,3.0,378.0,NaN,0.0,0.0,1.0,1.0,NaN,300.0,2.0,0.0,0.0
2,https://immovlan.be/en/detail/apartment/for-sa...,1190.0,Vorst,Apartment,apartment,385000.0,for sale,2.0,100.0,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,0.0,NaN
3,https://immovlan.be/en/detail/residence/for-sa...,7100.0,La Louvière,House,residence,135000.0,for sale,3.0,125.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,2.0,0.0,NaN
5,https://immovlan.be/en/detail/residence/for-sa...,2160.0,Wommelgem,House,residence,284000.0,for sale,3.0,180.0,NaN,0.0,0.0,0.0,1.0,240.0,295.0,2.0,0.0,0.0
6,https://immovlan.be/en/detail/residence/for-sa...,6660.0,Houffalize,House,residence,299000.0,for sale,4.0,124.0,3.0,0.0,0.0,1.0,1.0,NaN,441.0,3.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13244,https://immovlan.be/en/detail/residence/for-sa...,9190.0,Stekene,House,residence,450000.0,for sale,3.0,170.0,NaN,0.0,0.0,0.0,1.0,NaN,300.0,3.0,0.0,4.0
13245,https://immovlan.be/en/detail/apartment/for-sa...,1030.0,Schaarbeek,Apartment,apartment,229000.0,for sale,1.0,72.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,0.0,1.0
13246,https://immovlan.be/en/detail/residence/for-sa...,6470.0,Sautin,House,residence,199000.0,for sale,3.0,134.0,NaN,0.0,1.0,1.0,1.0,NaN,1497.0,NaN,0.0,NaN
13247,https://immovlan.be/en/detail/residence/for-sa...,1200.0,Sint-Lambrechts-Woluwe,House,residence,1090000.0,for sale,5.0,243.0,2.0,0.0,0.0,1.0,1.0,NaN,237.0,2.0,0.0,1.0
13248,https://immovlan.be/en/detail/residence/for-sa...,2840.0,Rumst,House,residence,2300000.0,for sale,7.0,576.0,NaN,0.0,0.0,1.0,1.0,NaN,5778.0,4.0,0.0,2.0

In [40]:
properties

,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building
1,https://immovlan.be/en/detail/residence/for-sa...,2200.0,Herentals,House,residence,369000.0,for sale,3.0,378.0,NaN,0.0,0.0,1.0,1.0,NaN,300.0,2.0,0.0,0.0
2,https://immovlan.be/en/detail/apartment/for-sa...,1190.0,Vorst,Apartment,apartment,385000.0,for sale,2.0,100.0,NaN,0.0,0.0,1.0,0.0,0.0,NaN,NaN,0.0,NaN
3,https://immovlan.be/en/detail/residence/for-sa...,7100.0,La Louvière,House,residence,135000.0,for sale,3.0,125.0,1.0,0.0,0.0,0.0,1.0,NaN,NaN,2.0,0.0,NaN
5,https://immovlan.be/en/detail/residence/for-sa...,2160.0,Wommelgem,House,residence,284000.0,for sale,3.0,180.0,NaN,0.0,0.0,0.0,1.0,240.0,295.0,2.0,0.0,0.0
6,https://immovlan.be/en/detail/residence/for-sa...,6660.0,Houffalize,House,residence,299000.0,for sale,4.0,124.0,3.0,0.0,0.0,1.0,1.0,NaN,441.0,3.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13244,https://immovlan.be/en/detail/residence/for-sa...,9190.0,Stekene,House,residence,450000.0,for sale,3.0,170.0,NaN,0.0,0.0,0.0,1.0,NaN,300.0,3.0,0.0,4.0
13245,https://immovlan.be/en/detail/apartment/for-sa...,1030.0,Schaarbeek,Apartment,apartment,229000.0,for sale,1.0,72.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,0.0,1.0
13246,https://immovlan.be/en/detail/residence/for-sa...,6470.0,Sautin,House,residence,199000.0,for sale,3.0,134.0,NaN,0.0,1.0,1.0,1.0,NaN,1497.0,NaN,0.0,NaN
13247,https://immovlan.be/en/detail/residence/for-sa...,1200.0,Sint-Lambrechts-Woluwe,House,residence,1090000.0,for sale,5.0,243.0,2.0,0.0,0.0,1.0,1.0,NaN,237.0,2.0,0.0,1.0
13248,https://immovlan.be/en/detail/residence/for-sa...,2840.0,Rumst,House,residence,2300000.0,for sale,7.0,576.0,NaN,0.0,0.0,1.0,1.0,NaN,5778.0,4.0,0.0,2.0

In [41]:
# Change types
## to string
properties["Zip code"]=properties["Zip code"].astype(int).astype(str)

## to int
floats_col=properties.select_dtypes('float64').columns
floats_col
properties[floats_col]=properties[floats_col].astype("Int64")

properties.dtypes

URL                         str
Zip code                    str
City                        str
Type of property            str
Subtype of property         str
Price                     Int64
Type of sale                str
Number of rooms           Int64
Living Area               Int64
Fully equipped kitchen    Int64
Furnished                 Int64
Open fire                 Int64
Terrace                   Int64
Garden                    Int64
Garden area               Int64
Surface of the land       Int64
Number of facades         Int64
Swimming pool             Int64
State of the building     Int64
dtype: object

In [42]:
# Change column names
properties.columns=['url', 'zip_code', 'city', 'type_of_property',
       'subtype_of_property','price', 'type_of_sale',
       'number_of_rooms', 'living_area', 'fully_equipped_kitchen', 'furnished',
       'open_fire', 'terrace', 'garden', 'garden_area',
       'surface_of_the_land', 'number_of_facades', 'swimming_pool',
       'state_of_the_building']
properties

,url,zip_code,city,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,living_area,fully_equipped_kitchen,furnished,open_fire,terrace,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
1,https://immovlan.be/en/detail/residence/for-sa...,2200,Herentals,House,residence,369000,for sale,3,378,<NA>,0,0,1,1,<NA>,300,2,0,0
2,https://immovlan.be/en/detail/apartment/for-sa...,1190,Vorst,Apartment,apartment,385000,for sale,2,100,<NA>,0,0,1,0,0,<NA>,<NA>,0,<NA>
3,https://immovlan.be/en/detail/residence/for-sa...,7100,La Louvière,House,residence,135000,for sale,3,125,1,0,0,0,1,<NA>,<NA>,2,0,<NA>
5,https://immovlan.be/en/detail/residence/for-sa...,2160,Wommelgem,House,residence,284000,for sale,3,180,<NA>,0,0,0,1,240,295,2,0,0
6,https://immovlan.be/en/detail/residence/for-sa...,6660,Houffalize,House,residence,299000,for sale,4,124,3,0,0,1,1,<NA>,441,3,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13244,https://immovlan.be/en/detail/residence/for-sa...,9190,Stekene,House,residence,450000,for sale,3,170,<NA>,0,0,0,1,<NA>,300,3,0,4
13245,https://immovlan.be/en/detail/apartment/for-sa...,1030,Schaarbeek,Apartment,apartment,229000,for sale,1,72,1,0,0,0,0,0,<NA>,3,0,1
13246,https://immovlan.be/en/detail/residence/for-sa...,6470,Sautin,House,residence,199000,for sale,3,134,<NA>,0,1,1,1,<NA>,1497,<NA>,0,<NA>
13247,https://immovlan.be/en/detail/residence/for-sa...,1200,Sint-Lambrechts-Woluwe,House,residence,1090000,for sale,5,243,2,0,0,1,1,<NA>,237,2,0,1
13248,https://immovlan.be/en/detail/residence/for-sa...,2840,Rumst,House,residence,2300000,for sale,7,576,<NA>,0,0,1,1,<NA>,5778,4,0,2

In [52]:
properties.to_csv("../../data/simon-data/properties-1-cleaned.csv")
houses=properties[properties.type_of_property=='House'].reset_index(drop=True)
apartments=properties[properties.type_of_property=='Apartment'].reset_index(drop=True)
houses
apartments

,url,zip_code,city,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,living_area,fully_equipped_kitchen,furnished,open_fire,terrace,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
0,https://immovlan.be/en/detail/apartment/for-sa...,1190,Vorst,Apartment,apartment,385000,for sale,2,100,<NA>,0,0,1,0,0,<NA>,<NA>,0,<NA>
1,https://immovlan.be/en/detail/apartment/for-sa...,1700,Dilbeek,Apartment,apartment,394000,for sale,3,120,<NA>,0,0,1,0,0,<NA>,<NA>,0,1
2,https://immovlan.be/en/detail/apartment/for-sa...,6600,Bastogne,Apartment,apartment,250000,for sale,3,141,<NA>,0,0,0,0,0,<NA>,<NA>,0,1
3,https://immovlan.be/en/detail/apartment/for-sa...,7170,Manage,Apartment,apartment,115000,for sale,2,90,<NA>,0,0,1,0,0,<NA>,3,0,2
4,https://immovlan.be/en/detail/studio/for-sale/...,1000,Brussels,Apartment,studio,200000,for sale,0,32,3,0,0,1,0,0,<NA>,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5782,https://immovlan.be/en/detail/apartment/for-sa...,1200,Sint-Lambrechts-Woluwe,Apartment,apartment,365000,for sale,4,122,2,0,1,1,0,0,<NA>,4,0,0
5783,https://immovlan.be/en/detail/apartment/for-sa...,1020,Laken,Apartment,apartment,399000,for sale,3,133,2,0,0,1,0,0,<NA>,2,0,4
5784,https://immovlan.be/en/detail/apartment/for-sa...,1785,Merchtem,Apartment,apartment,248000,for sale,1,58,<NA>,0,0,1,0,0,<NA>,2,0,1
5785,https://immovlan.be/en/detail/apartment/for-sa...,1090,Jette,Apartment,apartment,410000,for sale,4,197,<NA>,0,0,1,0,0,<NA>,3,0,0
5786,https://immovlan.be/en/detail/apartment/for-sa...,1030,Schaarbeek,Apartment,apartment,229000,for sale,1,72,1,0,0,0,0,0,<NA>,3,0,1

# Step 2 : Data Analysis

#### Now that the data has been collected and cleaned, it is time for the analysis. How many variables and inputs do you have? And so on...

#### Use the tools such as matplotlib/seaborn/plotly!

### Answer the following questions with a vizualization if appropriate:

#### - How many rows and columns?
#### - What is the correlation between the variables and the price? (Why might that be?)
#### - How are variables correlated to each other? (Why?)
#### - Which variables have the greatest influence on the price?
#### - Which variables have the least influence on the price?
#### - How many qualitative and quantitative variables are there? How would you transform these values into numerical values?
#### - Percentage of missing values per column?

In [44]:
# Rows and columns
properties.shape

# Percentage missing values per column
properties.isna().mean()

url                       0.000000
zip_code                  0.000000
city                      0.000000
type_of_property          0.000000
subtype_of_property       0.000000
price                     0.000000
type_of_sale              0.000000
number_of_rooms           0.016056
living_area               0.000000
fully_equipped_kitchen    0.640534
furnished                 0.000000
open_fire                 0.000000
terrace                   0.000000
garden                    0.000000
garden_area               0.310396
surface_of_the_land       0.529778
number_of_facades         0.206111
swimming_pool             0.000000
state_of_the_building     0.202097
dtype: float64