# CLEANING & FILLING THE DATAFRAME #

In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import datetime

In [87]:
df = pd.read_csv('../data/cleaned_properties_dataset_2026-03-11-11h31.csv', sep = ',')

## Analyzing the dataset ##

In [88]:
print(df.shape)
print(df.info())

(13301, 20)
<class 'pandas.DataFrame'>
RangeIndex: 13301 entries, 0 to 13300
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   URL                     13301 non-null  str
 1   Zip code                13295 non-null  float64
 2   City                    13295 non-null  str
 3   Type of property        13301 non-null  str
 4   Subtype of property     13301 non-null  str
 5   Price                   13107 non-null  float64
 6   Type of sale            13301 non-null  str
 7   Number of rooms         13043 non-null  float64
 8   Living Area             12456 non-null  float64
 9   Fully equipped kitchen  4663 non-null   float64
 10  Furnished               8353 non-null   float64
 11  Open fire               1141 non-null   float64
 12  Terrace                 12734 non-null  float64
 13  Terrace area            5711 non-null   float64
 14  Garden                  12332 non-null  float64
 15  Garden area             3048 non-null   float64
 16  Surface of the land     6323 non-null   float64
 17  Number of facades       10282 non-null  float64
 18  Swimming pool           4686 non-null   float64
 19  State of the building   10560 non-null  float64
dtypes: float64(15), str(5)
memory usage: 2.0 MB
None

In [89]:
df.describe(include='all')

,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Terrace area,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building
count,13301,13295.000000,13295,13301,13301,1.310700e+04,13301,13043.000000,12456.000000,4663.000000,8353.000000,1141.000000,12734.000000,5711.000000,12332.000000,3048.000000,6323.000000,10282.000000,4686.000000,10560.000000
unique,13301,NaN,1421,2,15,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,https://immovlan.be/en/detail/residence/for-sa...,NaN,Ukkel,House,residence,NaN,for sale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,473,7352,5966,NaN,13184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,3850.066491,NaN,NaN,NaN,4.388410e+05,NaN,3.109177,166.213712,2.239974,0.046450,0.310254,0.778232,25.003852,0.591550,864.797572,1223.857504,2.753939,0.086001,1.585606
std,NaN,2842.702119,NaN,NaN,NaN,5.275867e+05,NaN,17.257191,145.184358,0.707026,0.210471,0.462800,0.415453,52.019735,0.491567,3590.829895,3726.001804,0.845493,0.280395,1.378903
min,NaN,1000.000000,NaN,NaN,NaN,6.200000e+02,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,NaN,1180.000000,NaN,NaN,NaN,2.350000e+05,NaN,2.000000,91.000000,2.000000,0.000000,0.000000,1.000000,9.000000,0.000000,82.750000,225.000000,2.000000,0.000000,1.000000
50%,NaN,3070.000000,NaN,NaN,NaN,3.350000e+05,NaN,3.000000,134.000000,2.000000,0.000000,0.000000,1.000000,16.000000,1.000000,230.000000,500.000000,2.000000,0.000000,1.000000
75%,NaN,6215.000000,NaN,NaN,NaN,4.950000e+05,NaN,4.000000,197.000000,3.000000,0.000000,1.000000,1.000000,30.000000,1.000000,690.000000,1040.000000,4.000000,0.000000,2.000000
max,NaN,9990.000000,NaN,NaN,NaN,2.600000e+07,NaN,1962.000000,3500.000000,3.000000,1.000000,1.000000,1.000000,2968.000000,1.000000,118000.000000,101895.000000,8.000000,1.000000,4.000000

In [90]:
# Changing names of columns
df.columns = [col.lower().replace(' ', '_') for col in df.columns]
print(df.columns)

Index(['url', 'zip_code', 'city', 'type_of_property', 'subtype_of_property',
       'price', 'type_of_sale', 'number_of_rooms', 'living_area',
       'fully_equipped_kitchen', 'furnished', 'open_fire', 'terrace',
       'terrace_area', 'garden', 'garden_area', 'surface_of_the_land',
       'number_of_facades', 'swimming_pool', 'state_of_the_building'],
      dtype='str')

In [91]:
# deleting for duplicates
print(f'Number of duplicates: {df.duplicated().sum()}')
print()

df = df.drop_duplicates().reset_index(drop=True)

Number of duplicates: 0

In [92]:
# Changing the type of data
df['zip_code'] = df['zip_code'].apply(lambda x: str(int(x)) if pd.notnull(x) else x)

In [93]:
# cleaning spaces
subset = df.iloc[:, 0:7].select_dtypes(include=['string'])
df[subset.columns] = subset.apply(lambda x: x.str.strip())

In [94]:
# checking the percentage of missing data
print(df.isna().sum())
print("*" * 50)


for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

url                           0
zip_code                      6
city                          6
type_of_property              0
subtype_of_property           0
price                       194
type_of_sale                  0
number_of_rooms             258
living_area                 845
fully_equipped_kitchen     8638
furnished                  4948
open_fire                 12160
terrace                     567
terrace_area               7590
garden                      969
garden_area               10253
surface_of_the_land        6978
number_of_facades          3019
swimming_pool              8615
state_of_the_building      2741
dtype: int64
**************************************************
url - 0%
zip_code - 0%
city - 0%
type_of_property - 0%
subtype_of_property - 0%
price - 1%
type_of_sale - 0%
number_of_rooms - 2%
living_area - 6%
fully_equipped_kitchen - 65%
furnished - 37%
open_fire - 91%
terrace - 4%
terrace_area - 57%
garden - 7%
garden_area - 77%
surface_of_the_land - 52%
number_of_facades - 23%
swimming_pool - 65%
state_of_the_building - 21%

## FILLING THE DATA ##

In [95]:
df2 = df.copy()

In [96]:
# Who cares if there is no price?!

empty_price_mask = df2['price'].isna()
print(f"Empty prices properties to drop: {empty_price_mask.sum()}")

df2.dropna(subset=['price'], inplace = True)

Empty prices properties to drop: 194

In [97]:
df2.describe()

,price,number_of_rooms,living_area,fully_equipped_kitchen,furnished,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
count,1.310700e+04,12858.000000,12296.000000,4612.000000,8235.000000,1140.000000,12549.000000,5637.000000,12148.000000,2990.000000,6218.000000,10155.000000,4615.000000,10405.000000
mean,4.388410e+05,3.110359,165.519031,2.240460,0.046995,0.309649,0.777831,24.972681,0.589480,850.249498,1192.982149,2.750369,0.085157,1.579529
std,5.275867e+05,17.379392,144.480570,0.707541,0.211640,0.462552,0.415721,52.220811,0.491948,3509.100902,3618.089170,0.843832,0.279146,1.374559
min,6.200000e+02,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,2.350000e+05,2.000000,91.000000,2.000000,0.000000,0.000000,1.000000,9.000000,0.000000,82.000000,225.000000,2.000000,0.000000,1.000000
50%,3.350000e+05,3.000000,134.000000,2.000000,0.000000,0.000000,1.000000,16.000000,1.000000,226.500000,497.000000,2.000000,0.000000,1.000000
75%,4.950000e+05,4.000000,197.000000,3.000000,0.000000,1.000000,1.000000,30.000000,1.000000,671.750000,1030.000000,4.000000,0.000000,2.000000
max,2.600000e+07,1962.000000,3500.000000,3.000000,1.000000,1.000000,1.000000,2968.000000,1.000000,118000.000000,101895.000000,8.000000,1.000000,4.000000

In [98]:
df2[df2['garden_area']==0]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [99]:
df2[df2['terrace_area']==0]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [100]:
df2[(df2['garden_area']==0)&(df2['garden']==1)]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [101]:
print(f"Garden area == 0: {len(df2[df2['garden_area'] == 0])}")
print(f"Garden area == Empty: {df2['garden_area'].isna().sum()}")
print(f"Garden area == 0, while garden == 1: {len(df2[(df2['garden_area']==0)&(df2['garden']==1)])}")
print()
print(f"Terrace area == 0: {len(df2[df2['terrace_area'] == 0])}")
print(f"Terrace area == Empty: {df2['terrace_area'].isna().sum()}")
print(f"Terrace area == 0, while terrace == 1: {len(df2[(df2['terrace_area']==0)&(df2['terrace']==1)])}")

Garden area == 0: 0
Garden area == Empty: 10117
Garden area == 0, while garden == 1: 0

Terrace area == 0: 0
Terrace area == Empty: 7470
Terrace area == 0, while terrace == 1: 0

### Logical data-handling ###

In [102]:
# If there's a posiive area, then there's an object = 1
df2.loc[df2['garden_area'] > 0, 'garden'] = 1
df2.loc[df2['terrace_area'] > 0, 'terrace'] = 1

In [103]:
print(f"Garden area == 0, while garden == 1: {len(df2[(df2['garden_area']==0)&(df2['garden']==1)])}")
print(f"Terrace area == 0, while terrace == 1: {len(df2[(df2['terrace_area']==0)&(df2['terrace']==1)])}")

Garden area == 0, while garden == 1: 0
Terrace area == 0, while terrace == 1: 0

In [104]:

# If there's an object, but area is NaN or 0, then area is NaN (will fill with mean/median etc later)
df2.loc[(df2['garden'] == 1) & ((df2['garden_area'] == 0) | (df2['garden_area'].isna())), 'garden_area'] = np.nan
df2.loc[(df2['terrace'] == 1) & ((df2['terrace_area'] == 0) | (df2['terrace_area'].isna())), 'terrace_area'] = np.nan

print(f"Garden == Empty: {df2['garden'].isna().sum()}")
print(f"Terrace == Empty: {df2['terrace'].isna().sum()}")
print(f"Garden area == Empty: {df2['garden_area'].isna().sum()}")
print(f"Terrace area == Empty: {df2['terrace_area'].isna().sum()}")

Garden == Empty: 959
Terrace == Empty: 558
Garden area == Empty: 10117
Terrace area == Empty: 7470

In [105]:
# For the rest, if there's NaN, then there's NO object
df2['garden'] = df2['garden'].fillna(0)
df2['terrace'] = df2['terrace'].fillna(0)

print(f"Garden == Empty: {df2['garden'].isna().sum()}")
print(f"Terrace == Empty: {df2['terrace'].isna().sum()}")

Garden == Empty: 0
Terrace == Empty: 0

In [106]:
# If there's definitely NO object, then area is ZERO
df2.loc[df2['garden'] == 0, 'garden_area'] = 0
df2.loc[df2['terrace'] == 0, 'terrace_area'] = 0

print(f"Garden area == Empty: {df2['garden_area'].isna().sum()}")
print(f"Terrace area == Empty: {df2['terrace_area'].isna().sum()}")

print(f"Garden area is EMPTY while garden == 1: {len(df2.loc[(df2['garden_area'].isna())&(df2['garden']==1)])}")
print(f"Terrace area is EMPTY while terrace == 1: {len(df2.loc[(df2['terrace_area'].isna())&(df2['terrace']==1)])}")

Garden area == Empty: 4171
Terrace area == Empty: 4124
Garden area is EMPTY while garden == 1: 4171
Terrace area is EMPTY while terrace == 1: 4124

In [107]:
print(f"Number of properties with 'number_of_rooms' = 0 or > 100 before cleaning: {((df2["number_of_rooms"] == 0)|(df2["number_of_rooms"]>100)).sum()}")

df2.loc[((df2["number_of_rooms"] == 0)|(df2["number_of_rooms"]>100)), "number_of_rooms"] = np.nan

print(f"Number of properties with 'number_of_rooms' = 0 or > 100 after cleaning: {((df2["number_of_rooms"] == 0)|(df2["number_of_rooms"]>100)).sum()}")

Number of properties with 'number_of_rooms' = 0 or > 100 before cleaning: 110
Number of properties with 'number_of_rooms' = 0 or > 100 after cleaning: 0

In [108]:
# Define masks for logical anomalies based on property type
# For Houses: Anything less than 2 facades is considered missing/error
house_facade_anomaly = (df2['type_of_property'] == 'House') & (df2['number_of_facades'] < 2)

# For Apartments: Anything less than 1 facade is considered missing/error
apt_facade_anomaly = (df2['type_of_property'] == 'Apartment') & (df2['number_of_facades'] < 1)

# Apply changes: Replace anomalies with NaN to allow for hierarchical imputation later
df2.loc[house_facade_anomaly | apt_facade_anomaly, 'number_of_facades'] = np.nan

print(f"House facade anomalies fixed (< 2): {house_facade_anomaly.sum()}")
print(f"Apartment facade anomalies fixed (< 1): {apt_facade_anomaly.sum()}")
print(f"Total NaN in 'number_of_facades' now: {df2['number_of_facades'].isna().sum()}")

House facade anomalies fixed (< 2): 2
Apartment facade anomalies fixed (< 1): 0
Total NaN in 'number_of_facades' now: 2954

In [109]:
print(f"Number of rows with 0 living area before fixing the data: {df2[df2['living_area'] == 0].shape[0]}")

df2.loc[df2['living_area'] == 0, 'living_area'] = np.nan

print(f"Number of rows with 0 living area after fixing the data: {df2[df2['living_area'] == 0].shape[0]}")

Number of rows with 0 living area before fixing the data: 0
Number of rows with 0 living area after fixing the data: 0

In [ ]:
print(f"Houses with zero land surface: {((df2['type_of_property'] == 'House') & (df2['surface_of_the_land'] == 0)).sum()}")
print(f"Just FYI: Apartments with zero land surface: {((df2['type_of_property'] == 'Apartment') & (df2['surface_of_the_land'] == 0)).sum()}")

In [110]:
before = df2['surface_of_the_land'].isna().sum()

zero_land = (df2['surface_of_the_land'] == 0)

land_smaller_than_garden = (
    df2['surface_of_the_land'].notna() & 
    df2['garden_area'].notna() & 
    (df2['surface_of_the_land'] < df2['garden_area'])
)

house_land_anomaly_mask = (df2['type_of_property'] == 'House') & (zero_land | land_smaller_than_garden)

df2.loc[house_land_anomaly_mask, 'surface_of_the_land'] = np.nan

print(f"House anomalies fixed: {house_land_anomaly_mask.sum()}")


after = df2['surface_of_the_land'].isna().sum()

print(f"Было NaN: {before}")
print(f"Добавили аномалий: {house_land_anomaly_mask.sum()}")
print(f"Стало NaN: {after}")
print(f"Разница: {after - (before + house_land_anomaly_mask.sum())}")

House anomalies fixed: 33
Было NaN: 6889
Добавили аномалий: 33
Стало NaN: 6922
Разница: 0

In [111]:
# If not mentioned, then 0 ...
df2['swimming_pool'] = df2['swimming_pool'].fillna(0)
df2['open_fire'] = df2['open_fire'].fillna(0)
df2['furnished'] = df2['furnished'].fillna(0)
# Or most logical aka normal state
df2['state_of_the_building'] = df2['state_of_the_building'].fillna(2)
df2['fully_equipped_kitchen'] = df2['fully_equipped_kitchen'].fillna(1)



df2.describe(include='all')

,url,zip_code,city,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,living_area,fully_equipped_kitchen,furnished,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
count,13107,13107,13107,13107,13107,1.310700e+04,13107,12748.000000,12296.000000,13107.000000,13107.000000,13107.000000,13107.000000,8983.000000,13107.000000,8936.000000,6185.000000,10153.000000,13107.000000,13107.000000
unique,13107,877,1417,2,15,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,https://immovlan.be/en/detail/residence/for-sa...,1180,Ukkel,House,residence,NaN,for sale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,470,470,7237,5876,NaN,12990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,4.388410e+05,NaN,2.983291,165.519031,1.436484,0.029526,0.026932,0.744717,15.670823,0.546349,284.494852,1179.228779,2.750714,0.029984,1.666209
std,NaN,NaN,NaN,NaN,NaN,5.275867e+05,NaN,1.875999,144.480570,0.726001,0.169283,0.161891,0.436037,43.092023,0.497866,2068.881091,3393.027197,0.843558,0.170550,1.236453
min,NaN,NaN,NaN,NaN,NaN,6.200000e+02,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,2.350000e+05,NaN,2.000000,91.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,226.000000,2.000000,0.000000,1.000000
50%,NaN,NaN,NaN,NaN,NaN,3.350000e+05,NaN,3.000000,134.000000,1.000000,0.000000,0.000000,1.000000,8.000000,1.000000,0.000000,500.000000,2.000000,0.000000,2.000000
75%,NaN,NaN,NaN,NaN,NaN,4.950000e+05,NaN,4.000000,197.000000,2.000000,0.000000,0.000000,1.000000,20.000000,1.000000,84.000000,1031.000000,4.000000,0.000000,2.000000
max,NaN,NaN,NaN,NaN,NaN,2.600000e+07,NaN,100.000000,3500.000000,3.000000,1.000000,1.000000,1.000000,2968.000000,1.000000,118000.000000,86000.000000,8.000000,1.000000,4.000000

In [112]:
condition = (
    (df2['garden']==1) &
    (df2['garden_area']== 0)
)

df2[condition]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [113]:
condition = (
    (df2['garden']==0) &
    (df2['garden_area'] > 0)
)

df2[condition]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [114]:
condition = (
    (df2['terrace']==1) &
    (df2['terrace_area']== 0)
)

df2[condition]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [115]:
condition = (
    (df2['terrace']==0) &
    (df2['terrace_area'] > 0)
)

df2[condition]

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

In [116]:
# If there's a terrace, but no area
check_zeros = df2[(df2['terrace'] == 1) & (df2['terrace_area'] == 0)]

# How many terrace left NaN
check_nans = df2[(df2['terrace'] == 1) & (df2['terrace_area'].isna())]

print(f"Rows if terrace is '0': {len(check_zeros)}")
print(f"Rows where terrace became 'NaN': {len(check_nans)}")

Rows if terrace is '0': 0
Rows where terrace became 'NaN': 4124

In [117]:
df2.info()

<class 'pandas.DataFrame'>
Index: 13107 entries, 0 to 13300
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     13107 non-null  str
 1   zip_code                13107 non-null  str
 2   city                    13107 non-null  str
 3   type_of_property        13107 non-null  str
 4   subtype_of_property     13107 non-null  str
 5   price                   13107 non-null  float64
 6   type_of_sale            13107 non-null  str
 7   number_of_rooms         12748 non-null  float64
 8   living_area             12296 non-null  float64
 9   fully_equipped_kitchen  13107 non-null  float64
 10  furnished               13107 non-null  float64
 11  open_fire               13107 non-null  float64
 12  terrace                 13107 non-null  float64
 13  terrace_area            8983 non-null   float64
 14  garden                  13107 non-null  float64
 15  garden_area             8936 non-null   float64
 16  surface_of_the_land     6185 non-null   float64
 17  number_of_facades       10153 non-null  float64
 18  swimming_pool           13107 non-null  float64
 19  state_of_the_building   13107 non-null  float64
dtypes: float64(14), str(6)
memory usage: 2.1 MB

In [118]:
# Reality check
# Apartement + Garden -> Surface of Land != 0

condition = (
    (df2['type_of_property'] == 'Apartment') & 
    (df2['garden'] == 0) & 
    (df2['surface_of_the_land'].notna())
)
filtered_df = df2[condition]
filtered_df

Empty DataFrame
Columns: [url, zip_code, city, type_of_property, subtype_of_property, price, type_of_sale, number_of_rooms, living_area, fully_equipped_kitchen, furnished, open_fire, terrace, terrace_area, garden, garden_area, surface_of_the_land, number_of_facades, swimming_pool, state_of_the_building]
Index: []

### Creating regions/provinces/zip ###

In [122]:
# Introducing regions:  matching zip to region
def classify_region(zipcode):
    prefix = int(str(zipcode)[:2])

    if 10 <= prefix <= 12:
        return "Brussels"
    elif 15 <= prefix <= 39 or 80 <= prefix <= 99:
        return "Flanders"
    elif 40 <= prefix <= 79 or 13 <= prefix <= 14:
        return "Wallonia"
    else:
        return "Unknown"
        
df2['region'] = df2['zip_code'].apply(classify_region)
df2['region'] = df2['region'].astype('str')

In [120]:
df2.head()

,url,zip_code,city,type_of_property,subtype_of_property,price,type_of_sale,number_of_rooms,living_area,fully_equipped_kitchen,...,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building,region
0,https://immovlan.be/en/detail/residence/for-sa...,2250,Olen,House,residence,549000.0,for sale,4.0,317.0,1.0,...,0.0,1.0,NaN,1.0,NaN,391.0,2.0,0.0,1.0,Flanders
1,https://immovlan.be/en/detail/residence/for-sa...,4030,Grivegnée,House,residence,215000.0,for sale,3.0,100.0,3.0,...,0.0,1.0,24.0,0.0,0.0,92.0,2.0,0.0,3.0,Wallonia
2,https://immovlan.be/en/detail/penthouse/for-sa...,1000,Brussels,Apartment,penthouse,479000.0,for sale,3.0,126.0,1.0,...,0.0,1.0,27.0,0.0,0.0,NaN,2.0,0.0,1.0,Brussels
3,https://immovlan.be/en/detail/apartment/for-sa...,1040,Etterbeek,Apartment,apartment,530000.0,for sale,2.0,93.0,1.0,...,0.0,1.0,10.0,0.0,0.0,NaN,2.0,0.0,4.0,Brussels
4,https://immovlan.be/en/detail/chalet/for-sale/...,5541,Hastière-par-delà,House,chalet,139000.0,for sale,2.0,51.0,1.0,...,0.0,1.0,NaN,1.0,NaN,234.0,4.0,0.0,4.0,Wallonia

In [123]:
df2.info()

<class 'pandas.DataFrame'>
Index: 13107 entries, 0 to 13300
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     13107 non-null  str
 1   zip_code                13107 non-null  str
 2   city                    13107 non-null  str
 3   type_of_property        13107 non-null  str
 4   subtype_of_property     13107 non-null  str
 5   price                   13107 non-null  float64
 6   type_of_sale            13107 non-null  str
 7   number_of_rooms         12748 non-null  float64
 8   living_area             12296 non-null  float64
 9   fully_equipped_kitchen  13107 non-null  float64
 10  furnished               13107 non-null  float64
 11  open_fire               13107 non-null  float64
 12  terrace                 13107 non-null  float64
 13  terrace_area            8983 non-null   float64
 14  garden                  13107 non-null  float64
 15  garden_area             8936 non-null   float64
 16  surface_of_the_land     6185 non-null   float64
 17  number_of_facades       10153 non-null  float64
 18  swimming_pool           13107 non-null  float64
 19  state_of_the_building   13107 non-null  float64
 20  region                  13107 non-null  str
dtypes: float64(14), str(7)
memory usage: 2.2 MB

In [124]:
# Introducing provinces:  matching zip to province

zip_lookup = pd.read_csv('../data/provinces-zip.csv', sep = ',', usecols=['zipCode', 'province']).rename(columns={'zipCode': 'zip_code'})
zip_lookup['zip_code'] = zip_lookup['zip_code'].astype(str).str.strip()
zip_lookup_unique = zip_lookup.drop_duplicates(subset=['zip_code'])


# Dictionary to map local province names to English standards
province_translation = {
    'Vlaams-Brabant': 'Vlaams-Brabant',
    'Waals-Brabant': 'Brabant Wallon',
    'Antwerpen': 'Antwerp',
    'Oost-Vlaanderen': 'East Flanders',
    'West-Vlaanderen': 'West Flanders',
    'Henegouwen': 'Hainaut',
    'Luik': 'Liège',
    'Namen': 'Namur',
    'Luxemburg': 'Luxembourg',
    'Limburg': 'Limburg',
    'Brussel': 'Brussels',
    'Bruxelles': 'Brussels'
}


# Step 1: Pre-process the lookup table (zip_lookup)
# Replace province names using our translation dictionary
zip_lookup['province'] = zip_lookup['province'].replace(province_translation)

# Step 2: Initialize columns in the main dataframe
df2[['province']] = np.nan

# Step 3: Merge main data with the translated lookup table
df2 = df2.merge(
    zip_lookup_unique, 
    on='zip_code', 
    how='left', 
    suffixes=('', '_new')
)

# Step 4: Transfer new data to main columns
df2['province'] = df2['province_new']


# Step 5: Clean up temporary columns
df2.drop(columns=['province_new'], inplace=True)

# Final Check: Print unique province names to ensure translation worked
print("Provinces now in database:")
print(df2['province'].unique())

Provinces now in database:
<StringArray>
[      'Antwerpen',            'Luik',         'Brussel',           'Namen',
   'Waals-Brabant', 'West-Vlaanderen',  'Vlaams-Brabant',       'Luxemburg',
 'Oost-Vlaanderen',      'Henegouwen',         'Limburg']
Length: 11, dtype: str

In [125]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 13107 entries, 0 to 13106
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   url                     13107 non-null  str
 1   zip_code                13107 non-null  str
 2   city                    13107 non-null  str
 3   type_of_property        13107 non-null  str
 4   subtype_of_property     13107 non-null  str
 5   price                   13107 non-null  float64
 6   type_of_sale            13107 non-null  str
 7   number_of_rooms         12748 non-null  float64
 8   living_area             12296 non-null  float64
 9   fully_equipped_kitchen  13107 non-null  float64
 10  furnished               13107 non-null  float64
 11  open_fire               13107 non-null  float64
 12  terrace                 13107 non-null  float64
 13  terrace_area            8983 non-null   float64
 14  garden                  13107 non-null  float64
 15  garden_area             8936 non-null   float64
 16  surface_of_the_land     6185 non-null   float64
 17  number_of_facades       10153 non-null  float64
 18  swimming_pool           13107 non-null  float64
 19  state_of_the_building   13107 non-null  float64
 20  region                  13107 non-null  str
 21  province                13107 non-null  str
dtypes: float64(14), str(8)
memory usage: 2.2 MB

In [129]:
# 1. Define the columns you want at the beginning
leading_cols = ['price','region', 'province', 'zip_code', 'city']

# 2. Get the rest of the columns automatically
other_cols = [c for c in df2.columns if c not in leading_cols]

# 3. Reorder the dataframe by combining the lists
df2 = df2[leading_cols + other_cols]

# 4. Check the result
print(df2.columns.tolist())

['price', 'region', 'province', 'zip_code', 'city', 'url', 'type_of_property', 'subtype_of_property', 'type_of_sale', 'number_of_rooms', 'living_area', 'fully_equipped_kitchen', 'furnished', 'open_fire', 'terrace', 'terrace_area', 'garden', 'garden_area', 'surface_of_the_land', 'number_of_facades', 'swimming_pool', 'state_of_the_building']

In [130]:
df2

,price,region,province,zip_code,city,url,type_of_property,subtype_of_property,type_of_sale,number_of_rooms,...,furnished,open_fire,terrace,terrace_area,garden,garden_area,surface_of_the_land,number_of_facades,swimming_pool,state_of_the_building
0,549000.0,Flanders,Antwerpen,2250,Olen,https://immovlan.be/en/detail/residence/for-sa...,House,residence,for sale,4.0,...,0.0,0.0,1.0,NaN,1.0,NaN,391.0,2.0,0.0,1.0
1,215000.0,Wallonia,Luik,4030,Grivegnée,https://immovlan.be/en/detail/residence/for-sa...,House,residence,for sale,3.0,...,0.0,0.0,1.0,24.0,0.0,0.0,92.0,2.0,0.0,3.0
2,479000.0,Brussels,Brussel,1000,Brussels,https://immovlan.be/en/detail/penthouse/for-sa...,Apartment,penthouse,for sale,3.0,...,0.0,0.0,1.0,27.0,0.0,0.0,NaN,2.0,0.0,1.0
3,530000.0,Brussels,Brussel,1040,Etterbeek,https://immovlan.be/en/detail/apartment/for-sa...,Apartment,apartment,for sale,2.0,...,0.0,0.0,1.0,10.0,0.0,0.0,NaN,2.0,0.0,4.0
4,139000.0,Wallonia,Namen,5541,Hastière-par-delà,https://immovlan.be/en/detail/chalet/for-sale/...,House,chalet,for sale,2.0,...,0.0,0.0,1.0,NaN,1.0,NaN,234.0,4.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13102,369000.0,Flanders,Vlaams-Brabant,3271,Averbode,https://immovlan.be/en/detail/residence/for-sa...,House,residence,for sale,3.0,...,0.0,0.0,1.0,NaN,1.0,NaN,730.0,2.0,0.0,2.0
13103,285000.0,Wallonia,Luik,4219,Meeffe,https://immovlan.be/en/detail/residence/for-sa...,House,residence,for sale,4.0,...,0.0,0.0,1.0,NaN,1.0,222.0,487.0,4.0,0.0,1.0
13104,189000.0,Flanders,Antwerpen,2018,Antwerp,https://immovlan.be/en/detail/duplex/for-sale/...,Apartment,duplex,for sale,1.0,...,0.0,0.0,1.0,2.0,0.0,0.0,NaN,NaN,0.0,1.0
13105,249000.0,Brussels,Brussel,1080,Sint-Jans-Molenbeek,https://immovlan.be/en/detail/apartment/for-sa...,Apartment,apartment,for sale,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,1.0
13106,645000.0,Brussels,Brussel,1160,Oudergem,https://immovlan.be/en/detail/apartment/for-sa...,Apartment,apartment,for sale,3.0,...,0.0,0.0,1.0,NaN,0.0,0.0,NaN,NaN,0.0,4.0

In [ ]:
# Hierarchical imputation for 'geo_smart_index' (based on ZIP, Province, Region, Global)
import pandas as pd

def compute_geo_smart_index(X_train, X_test, y_train):
    """
    Создает колонку 'geo_smart_index' на основе средних цен из y_train.
    Использует иерархию: ZIP -> Province -> Region -> Global.
    """
    # Временный датафрейм для расчета групп (только Train!)
    temp_train = X_train.copy()
    temp_train['target_price'] = y_train

    # 1. Справочники средних цен (Расчет только по TRAIN)
    global_mean = y_train.mean()
    region_map = temp_train.groupby('region')['target_price'].mean()
    prov_map = temp_train.groupby('province')['target_price'].mean()
    zip_map = temp_train.groupby('zip_code')['target_price'].mean()
    
    # 2. Статистика количества продаж по ZIP в Train
    zip_counts = temp_train['zip_code'].value_counts()

    def transform_df(df):
        # А) Создаем "слои" цен для каждой строки
        # .map() сопоставляет текст (напр. 'Flanders') с числом (напр. 410000)
        val_region = df['region'].map(region_map).fillna(global_mean)
        val_prov = df['province'].map(prov_map).fillna(val_region)
        val_zip = df['zip_code'].map(zip_map).fillna(val_prov)
        
        # Б) Проверяем, сколько раз этот ZIP встречался в обучении
        counts = df['zip_code'].map(zip_counts).fillna(0)
        
        # В) ЛОГИКА "МАТРЕШКИ":
        # Если в обучении было >= 5 примеров для этого ZIP — берем его среднее.
        # Если меньше — берем среднее по Провинции.
        smart_index = val_zip.where(counts >= 5, val_prov)
        
        return smart_index

    # 3. Применяем трансформацию к обоим наборам
    train_geo_idx = transform_df(X_train)
    test_geo_idx = transform_df(X_test)
    
    return train_geo_idx, test_geo_idx

# --- ПРАВИЛЬНОЕ ПРИМЕНЕНИЕ В ТВОЕМ КОДЕ ---
# X_train['geo_smart_index'], X_test['geo_smart_index'] = compute_geo_smart_index(X_train, X_test, y_train)

In [ ]:
import pandas as pd
import numpy as np

def fill_missing_hierarchical(X_train, X_test, columns_to_fill, method='median'):
    """
    Заполняет пропуски в X_train и X_test на основе статистики из X_train.
    Иерархия: ZIP (если >= 5 записей) -> Province -> Region -> Global.
    """
    X_train_filled = X_train.copy()
    X_test_filled = X_test.copy()
    
    # Словари для хранения статистики (отчеты)
    reports = {'global': {}, 'region': {}, 'province': {}, 'zip': {}}
    
    for col in columns_to_fill:
        # 1. Считаем базовые метрики (пока в float64 для безопасности)
        if method == 'median':
            global_val = X_train[col].median()
            # Округляем сразу результат агрегации
            agg_func = lambda x: x.median().round()
        else:
            raw_mode = X_train[col].mode()
            global_val = raw_mode.iloc[0] if not raw_mode.empty else 0
            agg_func = lambda x: x.mode().iloc[0] if not x.mode().empty else None

        # 2. Формируем справочники-матрешки (округляем и храним как float/int)
        reports['global'][col] = round(global_val) if method == 'median' else global_val
        reports['region'][col] = X_train.groupby('region')[col].agg(agg_func)
        reports['province'][col] = X_train.groupby('province')[col].agg(agg_func)
        reports['zip'][col] = X_train.groupby('zip_code')[col].agg(agg_func)
        
        # Справочник частоты для ZIP
        zip_counts = X_train['zip_code'].value_counts()

        def transform_col(df, column_name):
            # Маппинг уровней
            val_region = df['region'].map(reports['region'][column_name]).fillna(reports['global'][column_name])
            val_prov = df['province'].map(reports['province'][column_name]).fillna(val_region)
            val_zip = df['zip_code'].map(reports['zip'][column_name]).fillna(val_prov)
            
            # Проверка порога доверия
            counts = df['zip_code'].map(zip_counts).fillna(0)
            substitute_values = val_zip.where(counts >= 5, val_prov)
            
            # ЗАПОЛНЕНИЕ: сначала fillna, потом приведение к Int64
            # Мы используем .astype(float) перед round, чтобы избежать NAType error
            return df[column_name].fillna(substitute_values).astype(float).round().astype('Int64')

        # Применяем трансформацию
        X_train_filled[col] = transform_col(X_train, col)
        X_test_filled[col] = transform_col(X_test, col)
        
    return X_train_filled, X_test_filled, reports

In [ ]:
# 1. Список колонок для медианы (площади)
cols_median = ['living_area', 'surface_of_the_land', 'terrace_area', 'garden_area']

# 2. Список колонок для моды (дискретные величины)
cols_mode = ['number_of_rooms', 'number_of_facades', 'state_of_the_building']

# Применяем медианное заполнение
X_train, X_test = fill_missing_hierarchical(X_train, X_test, cols_median, method='median')

# Применяем модальное заполнение
X_train, X_test = fill_missing_hierarchical(X_train, X_test, cols_mode, method='mode')

# И ТОЛЬКО ПОСЛЕ ЭТОГО создаем гео-индекс
X_train['geo_smart_index'], X_test['geo_smart_index'] = compute_geo_smart_index(X_train, X_test, y_train)

In [ ]:
# Updated version of the function to fill missing values with hierarchical imputation and return reports
import pandas as pd
import numpy as np

def fill_missing_hierarchical(df, stats_report):
    """
    Fills missing values using a hierarchical approach: ZIP -> Province -> Region -> Global.
    Differentiates between property types (HOUSE vs APARTMENT) for better accuracy.
    """
    # List of columns to fill
    target_columns = ['living_area', 'terrace_area', 'garden_area', 'surface_of_the_land', 'number_of_facades']
    
    for col in target_columns:
        if col not in df.columns:
            continue
            
        # We process each row where the target column is NaN
        missing_mask = df[col].isna()
        
        for idx, row in df[missing_mask].iterrows():
            z_code = row['zip_code']
            prov = row['province']
            reg = row['region']
            prop_type = row['property_type']
            
            fill_value = None
            
            # 1. Try to get median from ZIP code (most specific)
            try:
                # We assume stats_report['zip'][col] is a Series indexed by zip_code
                val = stats_report['zip'][col].get(z_code)
                if pd.notna(val):
                    fill_value = val
            except (KeyError, AttributeError):
                pass
            
            # 2. If still NaN, try Province level
            if pd.isna(fill_value):
                try:
                    val = stats_report['province'][col].get(prov)
                    if pd.notna(val):
                        fill_value = val
                except (KeyError, AttributeError):
                    pass
            
            # 3. If still NaN, try Region level
            if pd.isna(fill_value):
                try:
                    val = stats_report['region'][col].get(reg)
                    if pd.notna(val):
                        fill_value = val
                except (KeyError, AttributeError):
                    pass
            
            # 4. Final fallback: Global median (least specific)
            if pd.isna(fill_value):
                fill_value = stats_report['global'].get(col)
            
            # Apply the found value to the dataframe
            df.at[idx, col] = fill_value
            
    return df

In [ ]:
# 1. Calculate statistics for the report (using only training data!)
# Note: It's better to calculate these medians excluding 0 values 
# to get realistic "typical" sizes.
train_data_clean = X_train[X_train > 0] # Temporary filter for stats calculation

report = {
    'global': train_data_clean[['living_area', 'terrace_area', 'garden_area', 
                                'surface_of_the_land', 'number_of_facades']].median().to_dict(),
    
    'region': {col: train_data_clean.groupby('region')[col].median() 
               for col in ['living_area', 'terrace_area', 'garden_area', 'surface_of_the_land', 'number_of_facades']},
    
    'province': {col: train_data_clean.groupby('province')[col].median() 
                 for col in ['living_area', 'terrace_area', 'garden_area', 'surface_of_the_land', 'number_of_facades']},
    
    'zip': {col: train_data_clean.groupby('zip_code')[col].median() 
            for col in ['living_area', 'terrace_area', 'garden_area', 'surface_of_the_land', 'number_of_facades']}
}

# 2. Apply our cleaning masks to df2 before filling
# (The ones we discussed: converting illogical 0s to NaN)
# ... [Insert your facade and land area cleaning code here] ...

# 3. Call the hierarchical filling function
df2_filled = fill_missing_hierarchical(df2.copy(), report)

print("Missing values after hierarchical filling:")
print(df2_filled[['living_area', 'surface_of_the_land', 'number_of_facades']].isna().sum())