In [56]:
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt

In [57]:
# Load csv as df
path="../../data/simon-data/properties-2-extrapolated.csv"
properties=pd.read_csv(path,index_col=0)
properties=properties.reset_index()
properties.drop('index',axis=1)

,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,Fully equipped kitchen,Furnished,Open fire,Terrace,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building
0,https://immovlan.be/en/detail/residence/for-sa...,2200,Herentals,House,residence,369000,for sale,3.0,378,2.0,0,0,1,1,255.0,300.0,2.0,0,0.0
1,https://immovlan.be/en/detail/apartment/for-sa...,1190,Vorst,Apartment,apartment,385000,for sale,2.0,100,2.0,0,0,1,0,0.0,649.0,3.0,0,2.0
2,https://immovlan.be/en/detail/residence/for-sa...,7100,La Louvière,House,residence,135000,for sale,3.0,125,1.0,0,0,0,1,255.0,649.0,2.0,0,2.0
3,https://immovlan.be/en/detail/residence/for-sa...,2160,Wommelgem,House,residence,284000,for sale,3.0,180,2.0,0,0,0,1,240.0,295.0,2.0,0,0.0
4,https://immovlan.be/en/detail/residence/for-sa...,6660,Houffalize,House,residence,299000,for sale,4.0,124,3.0,0,0,1,1,255.0,441.0,3.0,0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11808,https://immovlan.be/en/detail/apartment/for-sa...,1090,Jette,Apartment,apartment,410000,for sale,4.0,197,2.0,0,0,1,0,0.0,649.0,3.0,0,0.0
11809,https://immovlan.be/en/detail/residence/for-sa...,9190,Stekene,House,residence,450000,for sale,3.0,170,2.0,0,0,0,1,255.0,300.0,3.0,0,4.0
11810,https://immovlan.be/en/detail/apartment/for-sa...,1030,Schaarbeek,Apartment,apartment,229000,for sale,1.0,72,1.0,0,0,0,0,0.0,649.0,3.0,0,1.0
11811,https://immovlan.be/en/detail/residence/for-sa...,6470,Sautin,House,residence,199000,for sale,3.0,134,2.0,0,1,1,1,255.0,1497.0,3.0,0,2.0
11812,https://immovlan.be/en/detail/residence/for-sa...,1200,Sint-Lambrechts-Woluwe,House,residence,1090000,for sale,5.0,243,2.0,0,0,1,1,255.0,237.0,2.0,0,1.0

In [58]:
# Assign Province and Region
properties[['Province','Region']]=np.nan

## Province by Zip
properties["Zip code"]=properties["Zip code"].astype(str)
provinces = {
    "1": "Brussels",
    "2": "Antwerp",
    "30": "Flemish Brabant", "31": "Flemish Brabant", "32": "Flemish Brabant",
    "33": "Flemish Brabant", "34": "Flemish Brabant", "35": "Flemish Brabant",
    "36": "Limburg", "37": "Limburg", "38": "Limburg", "39": "Limburg",
    "4": "Liège",
    "5": "Namur",
    "6": "Hainaut",
    "7": "Hainaut",
    "8": "West Flanders",
    "9": "East Flanders"
}

def get_province(x):
    return provinces.get(x[:2]) or provinces.get(x[0])

properties["Province"] = properties["Zip code"].apply(get_province)

## Region by Zip
regions = {
    "1": "Brussels",
    "2": "Flemish Region",
    "3": "Flemish Region",
    "4": "Walloon Region",
    "5": "Walloon Region",
    "6": "Walloon Region",
    "7": "Walloon Region",
    "8": "Flemish Region",
    "9": "Flemish Region"
}
def get_region(x):
    return regions.get(x[0])

properties["Region"]=properties["Zip code"].apply(get_region)

In [59]:
# Save csv
properties.to_csv("../../data/simon-data/properties-2b-located.csv")

In [60]:
properties.dtypes

index                       int64
URL                           str
Zip code                      str
City                          str
Type of property              str
Subtype of property           str
Price                       int64
Type of sale                  str
Number of rooms           float64
Living Area                 int64
Fully equipped kitchen    float64
Furnished                   int64
Open fire                   int64
Terrace                     int64
Garden                      int64
Garden area               float64
Surface of the land       float64
Number of facades         float64
Swimming pool               int64
State of the building     float64
Province                      str
Region                        str
dtype: object

In [61]:
properties

,index,URL,Zip code,City,Type of property,Subtype of property,Price,Type of sale,Number of rooms,Living Area,...,Open fire,Terrace,Garden,Garden area,Surface of the land,Number of facades,Swimming pool,State of the building,Province,Region
0,1,https://immovlan.be/en/detail/residence/for-sa...,2200,Herentals,House,residence,369000,for sale,3.0,378,...,0,1,1,255.0,300.0,2.0,0,0.0,Antwerp,Flemish Region
1,2,https://immovlan.be/en/detail/apartment/for-sa...,1190,Vorst,Apartment,apartment,385000,for sale,2.0,100,...,0,1,0,0.0,649.0,3.0,0,2.0,Brussels,Brussels
2,3,https://immovlan.be/en/detail/residence/for-sa...,7100,La Louvière,House,residence,135000,for sale,3.0,125,...,0,0,1,255.0,649.0,2.0,0,2.0,Hainaut,Walloon Region
3,5,https://immovlan.be/en/detail/residence/for-sa...,2160,Wommelgem,House,residence,284000,for sale,3.0,180,...,0,0,1,240.0,295.0,2.0,0,0.0,Antwerp,Flemish Region
4,6,https://immovlan.be/en/detail/residence/for-sa...,6660,Houffalize,House,residence,299000,for sale,4.0,124,...,0,1,1,255.0,441.0,3.0,0,4.0,Hainaut,Walloon Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11808,13243,https://immovlan.be/en/detail/apartment/for-sa...,1090,Jette,Apartment,apartment,410000,for sale,4.0,197,...,0,1,0,0.0,649.0,3.0,0,0.0,Brussels,Brussels
11809,13244,https://immovlan.be/en/detail/residence/for-sa...,9190,Stekene,House,residence,450000,for sale,3.0,170,...,0,0,1,255.0,300.0,3.0,0,4.0,East Flanders,Flemish Region
11810,13245,https://immovlan.be/en/detail/apartment/for-sa...,1030,Schaarbeek,Apartment,apartment,229000,for sale,1.0,72,...,0,0,0,0.0,649.0,3.0,0,1.0,Brussels,Brussels
11811,13246,https://immovlan.be/en/detail/residence/for-sa...,6470,Sautin,House,residence,199000,for sale,3.0,134,...,1,1,1,255.0,1497.0,3.0,0,2.0,Hainaut,Walloon Region
11812,13247,https://immovlan.be/en/detail/residence/for-sa...,1200,Sint-Lambrechts-Woluwe,House,residence,1090000,for sale,5.0,243,...,0,1,1,255.0,237.0,2.0,0,1.0,Brussels,Brussels